### ISSUE TITLE
不是自己的脚本就别首发了

### ISSUE THREAD

**Issue by djc-Sherlock** [zhaoboy9692/imaotai#1]
接口地址获取参数都不是自己的

**Comment by zhaoboy9692** [comment]
在逼逼 我就把接口关了

**Comment by djc-Sherlock** [comment]
笑死了，你关啊，有本事就关掉。反正我又不用的咯

**Comment by zhaoboy9692** [comment]
> 笑死了，你关啊，有本事就关掉。反正我又不用的咯

那你比比你妈 司马？

**Comment by djc-Sherlock** [comment]
我知道你很急，但是你别急。不要狗叫，好好说话。没人比你妈，真的别急，笑死

**Comment by zhaoboy9692** [comment]
> 
你要有病就去治  我写的脚本 还用不着你来比比   你他妈看清楚是谁首发 破解出来的

**Comment by djc-Sherlock** [comment]
破解啥？跟我有关系吗？

**Comment by zhaoboy9692** [comment]
> 破解啥？跟我有关系吗？

跟你没关系 那你要来喷？ 你有毒？还是司马了？

**Comment by djc-Sherlock** [comment]
喷你了嘛？别对号入座啊

**Comment by zhaoboy9692** [comment]
> 接口地址获取参数都不是自己的

你说的对 我抄袭别人了 我就发了 你能怎么？

**Comment by djc-Sherlock** [comment]
不怎么啊，拿证据干他啊
